. ${PORTDIR}/profiles/base/profile.bashrc

post_src_install() {
	[[ -d ${D} ]] || return 0
	[[ ${E_MACHINE} == "" ]] && return 0
	output="$( cd ${D} && scanelf -RmyBF%a . | grep -v -e ^${E_MACHINE} )"
	[[ $output != "" ]] && { echo; echo "* Wrong EM_TYPE. Expected ${E_MACHINE}"; echo -e "${output}"; echo; exit 1; }
}

# We dont functionize this to avoid sandboxing.
if [[ $EBUILD_PHASE == "postinst" ]]; then
	[[ $EMERGE_FROM != binary ]] && cross-fix-root ${CHOST}
fi
