name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: 00 4 * * *

jobs:
  crossdev:
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
        stage3:
          - latest # `openrc` (glibc+GCC) is tagged as `latest`
          - musl
    name: crossdev target=${{ matrix.target }} stage3=${{ matrix.stage3 }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create cross environment
        run: |
          docker run -v $(pwd):/workspace -w /workspace \
            docker.io/gentoo/stage3:${{ matrix.stage3 }} bash -c "
            # Install dependencies
            emerge --sync --quiet
            emerge \
              app-eselect/eselect-repository \
              sys-apps/config-site

            # Install crossdev
            make install

            # Create cross environment
            eselect repository create crossdev
            crossdev ${{ matrix.args }} --target ${{ matrix.target }}

            # zstd and its dependencies need both C and C++ toolchain. If any of them
            # is broken, the installation will fail.
            run: ${{ matrix.target }}-emerge app-arch/zstd
            "
